server:
  port: 8080
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/easyecxel?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
